/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ieugen' at '27.11.2014 16:16' with Gradle 2.1
 *
 * @author ieugen, @date 27.11.2014 16:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
